import matplotlib.pyplot as plt
import pandas as pd
x=pd.read_csv('https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto27/CasosNuevosSinSintomas.csv')
def MostarRegiones():
    print('1.- Arica y Parinacota')
    print('2.- Tarapacá')
    print('3.- Antofagasta')
    print('4.- Atacama')
    print('5.- Coquimbo')
    print('6.- Valparaíso')
    print('7.- Metropolitana')
    print("8.- O'Higgins")
    print('9.- Maule')
    print('10.- Ñuble')
    print('11.- Biobío')
    print('12.- Araucanía')
    print('13.- Los Ríos')
    print('14.- Los lagos')
    print('15.- Aysén')
    print('16.- Magallanes')

def MostrarCodigo():
    print('Arica y Parinacota = 15')
    print('Tarapacá = 01')
    print('Antofagasta = 02')
    print('Atacama = 03')
    print('Coquimbo = 04')
    print('Valparaíso = 05')
    print('Metropolitana = 13')
    print("O'Higgins = 06")
    print('Maule = 07')
    print('Ñuble = 084')
    print('Biobío = 08')
    print('Araucanía = 09')
    print('Los Ríos =14')
    print('Los lagos = 10')
    print('Aysén = 11')
    print('Magallanes = 12')
